name: Build ipwndfu

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install toolchains
        run: |
          brew update
          brew install llvm

          echo "$(brew --prefix llvm)/bin" >> $GITHUB_PATH

      - name: Install ARM GNU toolchain
        run: |
          brew install arm-none-eabi-gcc

      - name: Build
        run: |
          make

      - name: List output
        run: |
          ls -lah bin

      - name: Upload shellcodes
        uses: actions/upload-artifact@v4
        with:
          name: ipwndfu-shellcodes
          path: bin/